export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";
export const ERROR = "ERROR";
export const IN_PROGRESS = "IN_PROGRESS";
export const LOGOUT = "LOGOUT";

///// blood actions
export const SET_BLOOD_RECIEVER_BLOOD = "SET_BLOOD_RECIEVER_BLOOD";
export const SET_BLOOD_TYPE_BLOOD = "SET_BLOOD_TYPE_BLOOD";
export const SET_HOSPITAL_NAME_BLOOD = "SET_HOSPITAL_NAME_BLOOD";
export const SET_PICKUP_SERVICE_BLOOD = "SET_PICKUP_SERVICE_BLOOD";
export const UPLOAD_DOCUMENT_BLOOD = "UPLOAD_DOCUMENT_BLOOD";
export const SET_DATE_BLOOD = "SET_DATE_BLOOD";
export const SET_DISTANCE_TRAVEL_BLOOD = "SET_DISTANCE_TRAVEL_BLOOD";
export const SET_DETAILS_AVAILABLE_BLOOD = "SET_DETAILS_AVAILABLE_BLOOD";
export const SET_ENTIRE_DETAILS_BLOOD = "SAVE_ENTIRE_DATA_BLOOD";
export const SET_MOBILE_NUMBER = "SET_MOBILE_NUMBER";
export const SET_LATITUDE_AND_LONGITUDE = "SET_LATITUDE_AND_LONGITUDE";

///// oxygen actions

export const SET_OXYGEN_RECIEVER_OXYGEN = "SET_OXYGEN_RECIEVER_OXYGEN";
export const SET_HOSPITAL_NAME_ADDRESS_OXYGEN =
  "SET_HOSPITAL_NAME_ADDRESS_OXYGEN";
export const SET_FULL_GEAR_STATUS_OXYGEN = "SET_FULL_GEAR_STATUS_OXYGEN";
export const SET_CAN_DELIVER_OXYGEN = "SET_CAN_DELIVER_OXYGEN";
export const SET_DETAILS_AVAILABLE_OXYGEN = "SET_DETAILS_AVAILABLE_OXYGEN";
