export const SET_BLOOD_RECIEVER_BLOOD = "SET_BLOOD_RECIEVER_BLOOD";
export const SET_BLOOD_TYPE_BLOOD = "SET_BLOOD_TYPE_BLOOD";
export const SET_HOSPITAL_NAME_BLOOD = "SET_HOSPITAL_NAME_BLOOD";
export const SET_PICKUP_SERVICE_BLOOD = "SET_PICKUP_SERVICE_BLOOD";
export const UPLOAD_DOCUMENT_BLOOD = "UPLOAD_DOCUMENT_BLOOD";
export const SET_DATE_BLOOD = "SET_DATE_BLOOD";
export const SET_DISTANCE_TRAVEL_BLOOD = "SET_DISTANCE_TRAVEL_BLOOD";
